[[main]]
  identifier = "about"
  name = "關於"
  url = "about"
  weight = 1

[[main]]
  identifier = "archive"
  name = "歷史文章"
  url = "archive"
  weight = 2

[[main]]
  identifier = "gallery"
  name = "畫廊與分類標籤"
  url = "gallery"
  weight = 3
    
[[main]]
  parent = "gallery"
  name = "分類"
  url = "categories"

[[main]]
  parent = "gallery"
  name = "標籤"
  url = "tags"


[[main]]
  identifier = "posts"
  name = "最新文章"
  url = "posts"
  weight = 4
  
